### ISSUE TITLE
how to use the challenge mode

### ISSUE THREAD

**Issue by liuhuang31** [gorinars/dcase16-cnn#1]
Thanks for your sharing~. In develop mode,i run the code,and it can training the model for evaluate the development data. But how to use the challenge mode, to evaluate the challenge data. I'm very grateful　and happy if you look it.

**Comment by gorinars** [comment]
I do not quite remember having problem with this.

You should disable folds evaluation mode in config
dataset_evaluation_mode = 'full'
and also set your eval data set in
challenge_dataset 

Again, I did not run this code for almost one year. If you still have a problem, please clarify with logs

**Comment by liuhuang31** [comment]
Thanks a lot. 
ok , i will try it.
again, thanks.

**Comment by liuhuang31** [comment]
Hi, i tried it.
set dataset_evaluation_mode = 'full'
and also set eval data set in challenge_dataset

and appear the logs:
    Running system in challenge mode
    Feature extraction [Development data]
    ================================
    Train setup not available.

And i look the code, find when set mode = 'full' and eval = 'challenge_dataset'
when it jump to get the correspond training data, the method in the code is 
     def train(self, fold=0, scene_label=None):
            raise IOError('Train setup not available.')

So the above logs occurred, maybe i need to rewrite the  method? 
thanks.
